name: bazrin
description: "A new Flutter project."

  
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  skeletonizer: ^2.1.0+1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  icons_plus: ^5.0.0
  flutter_svg: ^2.2.1
  fl_chart: ^1.1.1
  hugeicons: ^1.1.1
  dotted_border: ^3.1.0
  image_picker: ^1.2.0
  flutter_quill: ^11.5.0
  permission_handler: ^12.0.1
  dropdown_search: ^6.0.2
  dio: ^5.9.0
  intl_phone_number_input: ^0.7.5
  file_picker: ^10.3.3
  flutter_gradient_text: ^1.0.1
  flutter_dotenv: ^6.0.0
  number_to_words: ^1.0.0
  drop_down_search_field: ^1.2.2
  toastification: ^3.0.3
  flutter_quill_delta_from_html: ^1.5.3
  vsc_quill_delta_to_html: ^1.0.5
  currency_picker: ^2.0.21
  barcode: ^2.2.9
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/splashicon.png
   - assets/images/bazrinlogo.png
   - assets/images/user.svg
   - assets/images/icons/google.png
   - assets/images/icons/fb.png
   - assets/images/icons/wa.png
   - assets/images/icons/google.png
   - assets/images/icons/face.svg
   - assets/images/icons/finger.svg
   - assets/images/icons/drawer.svg
   - assets/images/icons/box.svg
   - assets/images/icons/produckbox.svg
   - assets/images/icons/handshake.svg
   - assets/images/icons/due.svg
   - assets/images/icons/grow.svg
   - assets/images/icons/growline.svg
   - assets/images/icons/deshboard.svg
   - assets/images/icons/suppliers.svg
   - assets/images/icons/customar.svg
   - assets/images/icons/product.svg
   - assets/images/icons/purchases.svg
   - assets/images/icons/sales.svg
   - assets/images/icons/quotation.svg
   - assets/images/icons/account.svg
   - assets/images/icons/expense.svg
   - assets/images/icons/role.svg
   - assets/images/icons/filter.svg
   - assets/images/icons/staff.svg
   - assets/images/icons/promotion.svg
   - assets/images/icons/settings.svg
   - assets/images/icons/give.svg
   - assets/images/icons/take.svg
   - assets/images/icons/date.svg
   - assets/images/icons/takesmall.svg
   - assets/images/icons/3bar.svg
   - assets/images/icons/barcode.svg
   - assets/images/
   - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#0D7D4C"
  image: assets/images/bazrinlogo.png
  android_gravity: center
  fullscreen: true

  android_12:

    color: "#0D7D4C"

    